<a href="https://colab.research.google.com/github/sim12ran/Data-science-Journey-ML-in-Python-/blob/main/pythonndlibraryforML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
friends=["simran","Simpi","Akarshan","sristy","mummy","papa"]
for name in friends:
  if(name.startswith('A')):
   print(f"Superstar ({name})")
  else:
   print(name)




simran
Simpi
Superstar (Akarshan)
sristy
mummy
papa


In [ ]:
#creating the 1d array in numpy

import numpy as np
arr_1d=np.array([1,2,3,4])
print(arr_1d)
type(arr_1d)
arr_1d.ndim



[1 2 3 4]


1

In [ ]:
#to add cell above:- ctrl+a
#to add cell below:- ctrl+b

In [ ]:
#creating 2d array in numpy
arr_2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(arr_2d)
print("dimension of array created is",arr_2d.ndim)
print("types of datatype is",type(arr_2d))
print("size of array is (no of elements):",arr_2d.size)
#to find the row and column of an array is:
print("row and column of array is",arr_2d.shape)
#to find the datatype of array is:
print("datatype of array is",arr_2d.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
dimension of array created is 2
types of datatype is <class 'numpy.ndarray'>
size of array is (no of elements): 16
row and column of array is (4, 4)
datatype of array is int64


# **To create the 1s matrix**




In [ ]:
mx_1s=np.array([[1,1,1,1],[1,1,1,1],[1,1,1,1]])
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
#function in numpy that help sto create the matrix of any size with initializing with value 1
mx_1s=np.ones(5)    # here 5 is shape means column and will give the float type value
print(mx_1s)
print(mx_1s.dtype)  # this will print datatype


[1. 1. 1. 1. 1.]
float64


In [ ]:
#function to create the matrix of any size and of anydatatype
max_1s=np.ones((3,4), dtype=int)
print(max_1s)

#function to create matrix of 3 by 4 size initializing with 0
max_0s=np.zeros((3,4), dtype=int)
print(max_0s)

#function to create matrix of 3 by 4 size initializing with boolean value
max_0s=np.zeros((3,4), dtype=bool)
print(max_0s)

#

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[False False False False]
 [False False False False]
 [False False False False]]


In [40]:
# create matrix of string type
mx_0s=np.zeros((3,4),dtype=str)
print(mx_0s)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [43]:
#create a empty string

em_str=''
print(bool(em_str))

False


In [46]:
# use empty function to create empty matrix
em_mx=np.empty((3,3))
print(em_mx)


[[3.67300381e-315 0.00000000e+000 9.75202465e-044]
 [3.93616345e-315 0.00000000e+000 0.00000000e+000]
 [9.88131292e-324 0.00000000e+000 2.13436359e-321]]


## ***Numpy functions:***

**arange**

In [100]:
#np.arange(start,end,steps) to create 1d array
ar_1d=np.arange(1,13)
print(ar_1d)
#---------------------------------
print("\n")
even_arr=np.arange(1,13,3)
print(even_arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


[ 1  4  7 10]


**Linspace()**:- It defines the range and how many value i need btw the range

In [101]:
# create a range and no of value btw the range

value=np.linspace(1,13,5)
print(value)

[ 1.  4.  7. 10. 13.]


**reshape()**:-This function define the conversion of 1D array into mlti-dimensional array.

In [102]:
# we have a 1D array
ar_1d=np.array([1,2,3,4,5,6])
print(ar_1d)
print("\n")

# now convert the 1D array into 2D array
ar_2d=ar_1d.reshape(2,3)
print("2D array is",ar_2d)
print("\n")

# now convert 1d array into 3D array and must focus on no elements in 1d arrya using which we will create multi array
ar_3d=ar_1d.reshape(2,3,1)
print("3D array is",ar_3d)


[1 2 3 4 5 6]


2D array is [[1 2 3]
 [4 5 6]]


3D array is [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [103]:
#create 2d array from 1d array
ar=np.arange(1,13).reshape(2,6)
print(ar)



[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


**ravel()**:-This function convert multi-dimensional array into 1d array

In [104]:
#conversion of multi array into 1d arr using ravel fxn

arr_1d=ar.ravel()
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


**flatten()**:-similarly this function is used to convert the multi array into 1d array

In [105]:
#conversion of multi array into 1d arr using flatten fxn

print((ar.flatten()))

[ 1  2  3  4  5  6  7  8  9 10 11 12]


**transpose()**:-this fxn convert row into column

In [106]:
mtrx=np.array([1,2,3,4,5,6])
print(mtrx.reshape(2,3))
print(mtrx.transpose())


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


# **Mathematics Operation using numpy**

In [116]:
import numpy as np
# matrix1 is
arr1=np.arange(1,10).reshape(3,3)
# matrix2 is
arr2=np.arange(11,20).reshape(3,3)
print(arr1,"\n")
print(arr2,"\n")
# add two matrix from 1st method:-
print("sum of two matrix is","\n",arr1+arr2)
# add 2 matrix from 2nd method


[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[11 12 13]
 [14 15 16]
 [17 18 19]] 

sum of two matrix is 
 [[12 14 16]
 [18 20 22]
 [24 26 28]]
